/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java3;
import org.junit.jupiter.api.Test;

class AppTest {
    @Test void testHello() {
        // new Graphic("Graphic");
    }
}
